---
stages:
    - check_develop
    - check_master

# #### Templates - BoF
.tmpl_check: &tmpl_check
    image: ${REGISTRY_IMAGES}
    script:
        - |
            for script in $(echo ${CI_PROJECT_DIR}/ci/scripts/[0-9][0-9]-*.sh); do
                . ${script} "${CI_PROJECT_DIR}"
            done
# #### Templates - EoF


# #### Project check (merge request)
Develop:
    stage: check_develop
    only:
      refs:
        - merge_requests
        - schedules
        - develop
      variables:
        - $RELEASE == "develop"
    <<: *tmpl_check

# #### Project check for master branch (after merge request & schedules)
Prod:
    stage: check_master
    only:
      refs:
        - schedules
        - master
      variables:
        - $RELEASE == "prod"
    when: on_success
    <<: *tmpl_check
