---
stages:
    - scheduled_check_develop
    - scheduled_check_master
    - check_develop_before_merge
    - check_master_after_merge

# #### Templates - BoF
.tmpl_check: &tmpl_check
    image: ${REGISTRY_IMAGES}
    script:
        - |
            for script in $(echo ${CI_PROJECT_DIR}/ci/scripts/[0-9][0-9]-*.sh); do
                . ${script} "${CI_PROJECT_DIR}"
            done
# #### Templates - EoF

# #### Project check scheduled - BoF
Develop:
    stage: scheduled_check_develop
    only:
      refs:
        - schedules
      variables:
        - $RELEASE == "develop"
    <<: *tmpl_check

Prod:
    stage: scheduled_check_master
    only:
      refs:
        - schedules
      variables:
        - $RELEASE == "prod"
    <<: *tmpl_check
# #### Project check scheduled - EoF

# #### Project check before merge - BoF
Develop:
    stage: check_develop_before_merge
    only:
      refs:
        - merge_requests
    <<: *tmpl_check
    script:
        - "curl -X POST -F token=${TRIGGER_TOKEN} -F ref=master https://gitlab.com/api/v4/projects/10397707/trigger/pipeline"
# #### Project check before merge - EoF

# #### Project check after merge - BoF
Prod:
    stage: check_master_after_merge
    only:
      refs:
        - triggered
    when: on_success
    <<: *tmpl_check
# #### Project check after merge - EoF
