---
stages:
    - check_develop
    - check_master

# #### Templates - BoF
.tmpl_check: &tmpl_check
    image: ${REGISTRY_IMAGES}
    script:
        - |
            for script in $(echo ${CI_PROJECT_DIR}/ci/scripts/[0-9][0-9]-*.sh); do
                . ${script} "${CI_PROJECT_DIR}"
            done
# #### Templates - EoF


# #### Project check before merge - BoF
Develop:
    stage: check_develop
    only:
      refs:
        - schedules
        - develop
    <<: *tmpl_check
# #### Project check before merge - EoF

# #### Project check after merge - BoF
Prod:
    stage: check_develop
    only:
      refs:
        - schedules
        - merge_requests
        - master
    <<: *tmpl_check
# #### Project check after merge - EoF
