---
stages:
    - check_develop
    - check_master

# #### Templates - BoF
.tmpl_check: &tmpl_check
    image: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/mysb_images/project_check/project_check:latest
    script:
        - |
            for script in $(echo ${CI_PROJECT_DIR}/ci/scripts/[0-9][0-9]-*.sh); do
                . ${script} "${CI_PROJECT_DIR}"
            done
# #### Templates - EoF


# #### Project check (merge request)
project_check_develop:
    stage: check_develop
    only:
      refs:
        - merge_requests
    allow_failure: false
    <<: *tmpl_check


# #### Project check for master branch (after merge request & schedules)
project_check_master:
    stage: check_master
    only:
      refs:
        - master
        - schedules
    when: on_success
    <<: *tmpl_check
